version: "3.3"
services:
    athenaquery:
        image: athquery_img
        container_name: athquery_inst
        build: 
            context: .
        ports:
            - '9002:9002'
        environment:
            - NODE_ENV=docker
        volumes:
            - athquerydata:/usr/src/app
        networks:
            - athquerynetwork
        links:
            - 'dbcomponent:mysql'
    dbcomponent:
        image: mariadb
        container_name: restaurateur_inst
        environment:
            - MYSQL_DATABASE=restaurateurmodels
            - MYSQL_ROOT_PASSWORD=test
        volumes:
            - ./dbconfig:/etc/mysql/conf.d:ro
            - ./dbconfig:/docker-entrypoint-initdb.d:ro
            - restaurateurdata:/var/lib/mysql
        ports:
            - '9003:9003'
        networks:
            - athquerynetwork
networks:
    athquerynetwork:
        driver: bridge
volumes:
    athquerydata:
    restaurateurdata: