version: "3.3"
services:
    athenaquery:
        image: athquery_img
        container_name: athquery_inst
        build: 
            context: .
        ports:
            - '8099:8099'
        environment:
            - NODE_ENV=docker
        volumes:
            - athquerydata:/usr/src/app
        networks:
            - athquerynetwork
networks:
    athquerynetwork:
        driver: bridge
volumes:
    athquerydata: